/**
 * Production Express Server for Single Page Application (SPA)
 * 
 * This file configures the production Express server that serves the built application
 * as a client-side React SPA. It handles static file serving, API routes,
 * and serves the main HTML file for all routes.
 * 
 * Features:
 * - Static file serving for production builds
 * - API route handling
 * - SPA fallback routing
 * - Clean client-side React rendering
 */

import express from 'express'
import path from 'path'
import fs from 'fs'
import apiRoutes from './routes/api'

// Initialize Express application
const app = express()
const PORT = process.env.PORT || 3000

/**
 * Configure Express middleware
 * - JSON parsing for API requests
 * - URL-encoded form data parsing
 */
app.use(express.json())
app.use(express.urlencoded({ extended: true }))

/**
 * Serve static assets from the built client directory
 * This includes CSS, JavaScript, images, and other static files
 * generated by the Vite build process
 */
app.use(express.static(path.join(__dirname, '../dist/client')))

/**
 * Mount API routes under /api prefix
 * All API endpoints will be available at /api/*
 */
app.use('/api', apiRoutes)

/**
 * SPA fallback handler for all routes
 * 
 * This catch-all route handler serves the main HTML file for all non-API routes,
 * allowing React Router to handle client-side routing.
 */
app.get('*', (req, res) => {
  try {
    // Read the built HTML template generated by Vite
    const indexPath = path.join(__dirname, '../dist/client/index.html')
    const html = fs.readFileSync(indexPath, 'utf-8')
    
    // Send the HTML file - React will render on the client
    res.status(200).set({ 'Content-Type': 'text/html' }).end(html)
  } catch (e) {
    // Log errors for debugging
    console.error('Static file serving error:', e)
    
    // Send generic error response
    res.status(500).end('Internal Server Error')
  }
})

/**
 * Start the production server
 * Listens on the specified port and logs startup information
 */
app.listen(PORT, () => {
  console.log(`🚀 Production server running on http://localhost:${PORT}`)
  console.log(`📁 Serving static files from: ${path.join(__dirname, '../dist/client')}`)
  console.log(`🔗 API routes available at: http://localhost:${PORT}/api`)
})

export default app